shellEmulator: true

packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react:
    react: "^19.2.0"
    react-dom: "^19.2.0"
    "@tanstack/react-query": "^5.90.21"
    "@types/react": "19.2.2"
    "@types/react-dom": "19.2.2"

  server:
    "@hono/node-server": "^1.19.9"
    "@hono/zod-openapi": "^1.2.2"
    "@scalar/hono-api-reference": "^0.9.46"
    hono: "^4.12.3"
    zod: "^4.3.6"

  ui:
    "@base-ui/react": "^1.2.0"
    class-variance-authority: "^0.7.1"
    clsx: "^2.1.1"
    geist: "^1.7.0"
    lucide-react: "^0.575.0"
    next-themes: "^0.4.6"
    shadcn: "^3.8.5"
    "@tailwindcss/postcss": "^4.2.1"
    postcss: "^8.5.6"
    tailwind-merge: "^3.5.0"
    tw-animate-css: "^1.4.0"
    tailwindcss: "^4.2.1"

  env:
    "@t3-oss/env-core": "^0.13.10"
    "@t3-oss/env-nextjs": "^0.13.10"

  dev:
    typescript: "5.9.2"
    eslint: "^9.39.1"
    "@eslint-react/eslint-plugin": "^2.13.0"
    "@next/eslint-plugin-next": "^16.1.6"
    "@types/node": "22.15.3"
    eslint-plugin-react-hooks: "^7.0.1"
    eslint-plugin-react-refresh: "^0.5.2"
    next: "16.1.5"
    tsdown: "0.21.0-beta.2"
    tsx: "^4.21.0"

onlyBuiltDependencies:
  - esbuild
